/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.Banco;
import dao.TarefaDAO;
import model.Tarefa;
import java.sql.Date;
import java.sql.SQLException;
import java.time.DateTimeException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kaki
 */
public class MinhaAgendaDigital extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MinhaAgendaDigital.class.getName());
    private Banco banco;
    private DefaultTableModel tableModel;

    public MinhaAgendaDigital() {
        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbConcluida = new javax.swing.JComboBox<>();
        cxNome = new javax.swing.JTextField();
        cbCategoria = new javax.swing.JComboBox<>();
        cxDatahora = new javax.swing.JFormattedTextField();
        jTextField2 = new javax.swing.JTextField();
        btnCriarTarefa = new javax.swing.JButton();
        btnAtualizarTarefa = new javax.swing.JButton();
        btnBuscarTarefa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnExcluirTarefa = new javax.swing.JButton();
        btnDiagnostico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Adwaita Sans", 1, 18)); // NOI18N
        jLabel1.setText("Minha Agenda Virtual");

        jLabel2.setText("Nome da Tarefa");

        jLabel3.setText("Categoria");

        jLabel4.setText("Data");

        jLabel5.setText("Estado");

        cbConcluida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Concluido", "Nao concluido" }));
        cbConcluida.setName("cbConcluida"); // NOI18N

        cxNome.setName("txtTarefa"); // NOI18N

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trabalho", "Estudo", "Casa", "Lazer", "Saúde", "Outro" }));
        cbCategoria.setName("cbCategoria"); // NOI18N
        cbCategoria.addActionListener(this::cbCategoriaActionPerformed);

        cxDatahora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        cxDatahora.setToolTipText("");
        cxDatahora.setName("cxDatahora"); // NOI18N
        cxDatahora.addActionListener(this::cxDatahoraActionPerformed);

        jTextField2.setName("txtIdTarefa"); // NOI18N

        btnCriarTarefa.setText("Criar Tarefa");
        btnCriarTarefa.setName("btnCriarTarefa"); // NOI18N
        btnCriarTarefa.addActionListener(this::btnCriarTarefaActionPerformed);

        btnAtualizarTarefa.setLabel("Atualizar Tarefa");
        btnAtualizarTarefa.setName("btnAtualizarTarefa"); // NOI18N

        btnBuscarTarefa.setText("Buscar Tarefa");
        btnBuscarTarefa.setName("BtnBuscar"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setText("Digite o ID correspondente a tarefa");

        btnExcluirTarefa.setLabel("Excluir Tarefa");
        btnExcluirTarefa.setName("btnExcluirTarefa"); // NOI18N

        btnDiagnostico.setText("Diagnostico");
        btnDiagnostico.addActionListener(this::btnDiagnosticoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cxDatahora, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(btnDiagnostico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(cbConcluida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(btnExcluirTarefa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(btnCriarTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAtualizarTarefa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(10, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btnDiagnostico))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(btnCriarTarefa)
                    .addComponent(btnAtualizarTarefa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbConcluida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxDatahora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirTarefa)
                    .addComponent(btnBuscarTarefa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarTarefaActionPerformed(java.awt.event.ActionEvent evt) {
        atualizarTarefa();
    }

    private void btnBuscarTarefaActionPerformed(java.awt.event.ActionEvent evt) {
        buscarTarefa();
    }

    private void btnExcluirTarefaActionPerformed(java.awt.event.ActionEvent evt) {
        excluirTarefa();
    }
    private void btnCriarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarTarefaActionPerformed
        CriarTarefa();
    }//GEN-LAST:event_btnCriarTarefaActionPerformed

    private void cxDatahoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxDatahoraActionPerformed

    }//GEN-LAST:event_cxDatahoraActionPerformed

    private void cbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaActionPerformed
        String categoriaSelecionada = cbCategoria.getSelectedItem().toString();

        try {
            int idCategoria = obterIdCategoria(categoriaSelecionada);
            System.out.println("ID da categoria: " + idCategoria);

        } catch (CategoriaInvalidaException e) {

            JOptionPane.showMessageDialog(null, "Categoria inválida selecionada!");
        }


    }//GEN-LAST:event_cbCategoriaActionPerformed

    private void btnDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagnosticoActionPerformed
    diagnosticarErro();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDiagnosticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MinhaAgendaDigital().setVisible(true));
    }

    private void initCustomComponents() {
        banco = Banco.getBanco();
        setupTableModel();
        carregarTodasTarefas();

        btnAtualizarTarefa.addActionListener(this::btnAtualizarTarefaActionPerformed);
        btnBuscarTarefa.addActionListener(this::btnBuscarTarefaActionPerformed);
        btnExcluirTarefa.addActionListener(this::btnExcluirTarefaActionPerformed);
    }

    private void setupTableModel() {
        String[] colunas = {"ID", "Nome", "Categoria", "Data", "Estado"};
        tableModel = new DefaultTableModel(colunas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable1.setModel(tableModel);
    }

    private void listTabTarefas(List<Tarefa> tarefas) {
        tableModel.setRowCount(0);

        if (tarefas != null) {
            for (Tarefa tarefa : tarefas) {
                String categoria = obterNomeCategoria(tarefa.getIdcategoria());
                String estado = tarefa.isConcluida() ? "Concluída" : "Pendente";
                String data = tarefa.getDatahora() != null ? tarefa.getDatahora().toString() : "Não definida";

                tableModel.addRow(new Object[]{
                    tarefa.getId(),
                    tarefa.getNome(),
                    categoria,
                    data,
                    estado
                });
            }
        }
    }

    private void selLinTabTarefa(Tarefa tarefa) {
        if (tarefa != null) {
            for (int i = 0; i < tableModel.getRowCount(); i++) {
                if (tableModel.getValueAt(i, 0).equals(tarefa.getId())) {
                    jTable1.setRowSelectionInterval(i, i);
                    preencherCampos(tarefa);
                    break;
                }
            }
        }
    }

    private void preencherCampos(Tarefa tarefa) {
        jTextField2.setText(String.valueOf(tarefa.getId()));
        cxNome.setText(tarefa.getNome());
        cxDatahora.setValue(tarefa.getDatahora());
        cbConcluida.setSelectedItem(tarefa.isConcluida() ? "Concluido" : "Nao concluido");

        String nomeCategoria = obterNomeCategoria(tarefa.getIdcategoria());
        cbCategoria.setSelectedItem(nomeCategoria);
    }

    private void carregarTodasTarefas() {
        try {
            List<Tarefa> tarefas = banco.getTodasTarefas();
            listTabTarefas(tarefas);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao carregar tarefas: " + e.getMessage(),
                    "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void CriarTarefa() {
        try {
            String nome = cxNome.getText().trim();

            if (nome.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Nome da tarefa é obrigatório!",
                        "VALIDAÇÃO", JOptionPane.WARNING_MESSAGE);
                cxNome.requestFocus();
                return;
            }

            int idcategoria = obterIdCategoria(cbCategoria.getSelectedItem().toString());
            Date datahora = obterDataHora();
            boolean estado = obterEstado(cbConcluida.getSelectedItem().toString());

            Tarefa t = new Tarefa();
            t.setNome(nome);
            t.setIdcategoria(idcategoria);
            t.setDatahora(datahora);
            t.setConcluida(estado);

            if (banco.inserirTarefa(t)) {
                JOptionPane.showMessageDialog(this,
                        "Tarefa cadastrada com sucesso!",
                        "SUCESSO", JOptionPane.INFORMATION_MESSAGE);

                carregarTodasTarefas(); // Recarregar tabela
                selLinTabTarefa(banco.getTarefaPorNome(nome));
                limparCxs();
            }

        } catch (CategoriaInvalidaException cie) {
            JOptionPane.showMessageDialog(this,
                    "Categoria inválida!", "ERRO", JOptionPane.ERROR_MESSAGE);
            cbCategoria.requestFocus();
        } catch (DateTimeException dte) {
            JOptionPane.showMessageDialog(this,
                    "Data/hora inválida!", "ERRO", JOptionPane.ERROR_MESSAGE);
            cxDatahora.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro inesperado: " + e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
            limparCxs();
            cxNome.requestFocus();
        }
    }

    private void atualizarTarefa() {
        try {
            String idText = jTextField2.getText().trim();
            if (idText.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Selecione uma tarefa para atualizar!",
                        "VALIDAÇÃO", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int id = Integer.parseInt(idText);
            String nome = cxNome.getText().trim();

            if (nome.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Nome da tarefa é obrigatório!",
                        "VALIDAÇÃO", JOptionPane.WARNING_MESSAGE);
                cxNome.requestFocus();
                return;
            }

            int idcategoria = obterIdCategoria(cbCategoria.getSelectedItem().toString());
            Date datahora = obterDataHora();
            boolean estado = obterEstado(cbConcluida.getSelectedItem().toString());

            Tarefa t = new Tarefa();
            t.setId(id);
            t.setNome(nome);
            t.setIdcategoria(idcategoria);
            t.setDatahora(datahora);
            t.setConcluida(estado);

            if (banco.atualizarTarefa(t)) {
                JOptionPane.showMessageDialog(this,
                        "Tarefa atualizada com sucesso!",
                        "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                carregarTodasTarefas();
                limparCxs();
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "ID inválido!", "ERRO", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao atualizar: " + e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void buscarTarefa() {
        String nome = cxNome.getText().trim();
        if (!nome.isEmpty()) {
            try {
                Tarefa tarefa = banco.getTarefaPorNome(nome);
                if (tarefa != null) {
                    List<Tarefa> tarefas = List.of(tarefa);
                    listTabTarefas(tarefas);
                    selLinTabTarefa(tarefa);
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Tarefa não encontrada!", "INFO", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Erro na busca: " + e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            carregarTodasTarefas();
        }
    }

    private void excluirTarefa() {
        String idText = jTextField2.getText().trim();
        if (idText.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Selecione uma tarefa para excluir!",
                    "VALIDAÇÃO", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Confirma a exclusão desta tarefa?",
                "CONFIRMAR EXCLUSÃO",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                int id = Integer.parseInt(idText);

                if (banco.excluirTarefa(id)) {
                    JOptionPane.showMessageDialog(this,
                            "Tarefa excluída com sucesso!",
                            "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                    carregarTodasTarefas();
                    limparCxs();
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                        "ID inválido!", "ERRO", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Erro ao excluir: " + e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private int obterIdCategoria(String categoriaTexto) throws CategoriaInvalidaException {
        switch (categoriaTexto) {
            case "Trabalho":
                return 1;
            case "Estudo":
                return 2;
            case "Casa":
                return 3;
            case "Lazer":
                return 4;
            case "Saúde":
                return 5;
            case "Outro":
                return 6;
            default:
                throw new CategoriaInvalidaException();
        }
    }

    private String obterNomeCategoria(int idCategoria) {
        switch (idCategoria) {
            case 1:
                return "Trabalho";
            case 2:
                return "Estudo";
            case 3:
                return "Casa";
            case 4:
                return "Lazer";
            case 5:
                return "Saúde";
            case 6:
                return "Outro";
            default:
                return "Desconhecida";
        }
    }

    private boolean obterEstado(String estadoTexto) {
        return estadoTexto.equals("Concluido");
    }

    private Date obterDataHora() throws DateTimeException {
        try {
            if (cxDatahora.getValue() != null) {
                java.util.Date utilDate = (java.util.Date) cxDatahora.getValue();
                return new Date(utilDate.getTime());
            } else {
                return new Date(System.currentTimeMillis());
            }
        } catch (Exception e) {
            throw new DateTimeException("Data inválida");
        }
    }

    private void listTabTarefas() {

    }

    private void limparCxs() {
        cxNome.setText("");
        cbCategoria.setSelectedIndex(0);
        cxDatahora.setValue(null);
        cbConcluida.setSelectedIndex(0);
        jTextField2.setText("");
    }

    class CategoriaInvalidaException extends Exception {

        public CategoriaInvalidaException() {
            super("Categoria inválida");
        }
    }
    
    //Metodo para diagnosticar o erro do not supported yet
    
    // ✅ MÉTODO DE DIAGNÓSTICO - Adicione no JFrame
private void diagnosticarErro() {
    try {
        System.out.println("=== INICIANDO DIAGNÓSTICO ===");
        
        // Teste 1: Conexão com o banco
        System.out.println("1. Testando conexão...");
        if (banco.testarConexao()) {
            System.out.println("   ✅ Conexão OK");
        }
        
        // Teste 2: Listar tarefas
        System.out.println("2. Testando listar tarefas...");
        List<Tarefa> tarefas = banco.getTodasTarefas();
        System.out.println("   ✅ Listar tarefas: " + (tarefas != null ? tarefas.size() + " tarefas" : "FALHA"));
        
        // Teste 3: Buscar por nome
        System.out.println("3. Testando buscar por nome...");
        Tarefa tarefa = banco.getTarefaPorNome("Teste");
        System.out.println("   ✅ Buscar por nome: " + (tarefa != null ? "Encontrada" : "Não encontrada (normal)"));
        
        // Teste 4: Inserir tarefa
        System.out.println("4. Testando inserir tarefa...");
        Tarefa novaTarefa = new Tarefa();
        novaTarefa.setNome("Tarefa Teste " + System.currentTimeMillis());
        novaTarefa.setIdcategoria(1);
        novaTarefa.setDatahora(new Date(System.currentTimeMillis()));
        novaTarefa.setConcluida(false);
        
        boolean inserido = banco.inserirTarefa(novaTarefa);
        System.out.println("   ✅ Inserir tarefa: " + (inserido ? "SUCESSO" : "FALHA"));
        
        System.out.println("=== DIAGNÓSTICO COMPLETADO ===");
        
    } catch (Exception e) {
        System.err.println("❌ ERRO NO DIAGNÓSTICO: " + e.getMessage());
        e.printStackTrace(); // ⚠️ ISSO VAI MOSTRAR O "not supported yet" EXATO!
        
        JOptionPane.showMessageDialog(this, 
            "Erro no diagnóstico: " + e.getMessage(), 
            "ERRO DE DIAGNÓSTICO", JOptionPane.ERROR_MESSAGE);
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarTarefa;
    private javax.swing.JButton btnBuscarTarefa;
    private javax.swing.JButton btnCriarTarefa;
    private javax.swing.JButton btnDiagnostico;
    private javax.swing.JButton btnExcluirTarefa;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JComboBox<String> cbConcluida;
    private javax.swing.JFormattedTextField cxDatahora;
    private javax.swing.JTextField cxNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
